apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-nginx
  template:
    metadata:
      labels:
        app: custom-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-ssl
          mountPath: /etc/nginx/fullchain.pem
          subPath: fullchain.pem
        - name: nginx-ssl
          mountPath: /etc/nginx/privkey.pem
          subPath: privkey.pem
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: nginx-ssl
        secret:
          secretName: nginx-ssl-secret

---

apiVersion: v1
kind: Service
metadata:
  name: custom-nginx-service
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: custom-nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 30443
